final code push session task
vc-vishva/NodeJs__Task pull request #11
Opened 2023-05-29 07:19 UTC by vc-vishva

- perform session - cookies task

2023-05-29 07:31 UTC, gaurangviitorcloud requested changes

2023-05-29 07:31 UTC, gaurangviitorcloud commented on sign-up task/main.js
>    return bcrypt.compareSync(password, hashedPassword);
Please use async method of bcrypt

2023-05-29 08:48 UTC, gaurangviitorcloud requested changes

2023-05-29 08:48 UTC, gaurangviitorcloud commented on sign-up task/main.js
> + await fs.writeFile("db.json", JSON.stringify(data));
Stil for bcrypt you have used sync methods please use promises

2023-05-30 05:08 UTC, vc-mohit approved these changes

2023-05-30 05:09 UTC, vc-mohit commented
@gaurangviitorcloud: Please check the PR, she changed what you requested.

2023-06-05 06:53 UTC, gaurangviitorcloud approved these changes

2023-06-05 06:53 UTC, gaurangviitorcloud approved these changes

2023-06-05 06:54 UTC, merged