Feature/tip management
vc-vishva/NodeJs__Task pull request #20
Opened 2023-07-07 07:33 UTC by vc-vishva

tip - management task using typescript

2023-07-09 11:35 UTC, vc-mohit commented on tip-management-TS/src/models/tips.ts
> +    user_id: { type: String, required: true },
take ref from User Schema, this is not correct.

2023-07-09 11:37 UTC, vc-mohit commented on tip-management-TS/src/types/type.ts
this interfaces is required?

2023-07-09 12:00 UTC, vc-mohit commented on tip-management-TS/src/services/userService.ts
> +}): Promise<IUser> => {
why you destructure userdata object in params?

2023-07-09 12:10 UTC, vc-mohit commented on tip-management-TS/src/controller/userController.ts
need to change lot's of thing, we will discuss on this.

2023-07-09 12:16 UTC, vc-mohit requested changes
remove all consoles,
remove unused imports
remove commented code

2023-07-09 13:51 UTC, vc-vishva commented on tip-management-TS/src/services/userService.ts
> +}): Promise<IUser> => {
extract specific properties from the userdata object directly in the function parameter.

2023-07-10 13:45 UTC, vc-mohit commented on tip-management-TS/src/controller/userController.ts
> +    console.log("Error:", error);
remove console

2023-07-10 13:47 UTC, vc-mohit commented on tip-management-TS/src/middleware/verify.ts
remove all consoles

2023-07-10 13:55 UTC, vc-mohit commented on tip-management-TS/src/utils/response.ts
> +export const replaceMsg = (message: string, data: string) => {
what is the use of this function?

2023-07-10 13:56 UTC, vc-mohit commented on tip-management-TS/src/validation/tipValidation.ts
> +    .isLength({ min: 25 })
is the code working?

2023-07-10 13:57 UTC, vc-mohit commented on tip-management-TS/src/validation/userValidation.ts
same for this file

2023-07-10 13:57 UTC, vc-mohit commented on tip-management-TS/src/utils/apiError.ts
this file is required?

2023-07-10 14:47 UTC, vc-vishva commented on tip-management-TS/src/validation/userValidation.ts
yes

2023-07-11 05:18 UTC, vc-mohit commented on tip-management-TS/src/validation/tipValidation.ts
validation is not proper?

2023-07-11 05:21 UTC, vc-mohit commented on tip-management-TS/src/middleware/verify.ts
> +    res.status(401).send({ error: error });
why you are sending 2 times res?

2023-07-11 05:23 UTC, vc-mohit commented on tip-management-TS/src/middleware/verify.ts
> +export interface test {
change the name of Interface.

2023-07-11 05:24 UTC, vc-mohit requested changes
do all the changes, then I'll merge the PR.

2023-07-11 09:03 UTC, vc-mohit approved these changes

2023-07-11 09:09 UTC, merged